version: "3.9"

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: seoultrips-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: albatrips
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seoultrips-api
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=albatrips
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./server/static/uploads:/app/server/static/uploads
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db_data:
