version: "3.9"

services:
  api:
    build: .
    container_name: seoultrips-api
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app # 코드 hot reload
      - ./server/static/uploads:/app/server/static/uploads
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: mysql:8.0
    container_name: seoultrips-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: seoultrips
      MYSQL_USER: tripuser
      MYSQL_PASSWORD: trippass
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d # 덤프 자동 import

volumes:
  db_data:
